BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput:
            id: input_mile
            text: ''
            font_size: 48
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Button:
        text: 'Convert m to km'
    Label:
        id: output_label
        font_size: 48
        color: (1, 1, 0, 1)